[package]
name = "swarm-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/root.rs"

[dependencies]
blake3.workspace = true
directories.workspace = true
ed25519-dalek.workspace = true
postcard.workspace = true
rand_core.workspace = true
serde.workspace = true
thiserror.workspace = true
swarm-protocol = { path = "../swarm-protocol" }

[dev-dependencies]
tempfile.workspace = true
