[package]
name = "swarm-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/root.rs"

[dependencies]
blake3.workspace = true
hex.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true
