[package]
name = "swarm-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
libp2p.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
swarm-protocol = { path = "../swarm-protocol" }

[dev-dependencies]
rand_core.workspace = true
serde_json.workspace = true
tempfile.workspace = true
